### ISSUE TITLE
ERROR: Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by ipuppy2** [devilsen/CZXing#11]
编译报这个错误:
ERROR: Manifest merger failed with multiple errors, see logs
![image](https://user-images.githubusercontent.com/10703130/62057094-87166e00-b251-11e9-9649-aa286b6da963.png)
![image](https://user-images.githubusercontent.com/10703130/62057131-98f81100-b251-11e9-9258-c1584ddf9d57.png)

**Comment by devilsen** [comment]
你是要把androidx换成support吗？

**Comment by JiangXianKaiNan** [comment]
我也出现同样的问题了

**Comment by devilsen** [comment]
我尝试打出一个兼容的版本

**Comment by devilsen** [comment]
现在lib中移除了所有AndroidX相关的内容，应该可以了

**Comment by ipuppy2** [comment]
好尴尬, 换成 0.4.4 编译是通过了,可是安装时候,一直卡在那里

<img width="1129" alt="WX20190731-001629" src="https://user-images.githubusercontent.com/10703130/62146705-856ba980-b328-11e9-8ee7-7d5f28663ce7.png">

**Comment by ipuppy2** [comment]
项目是直接通过 as 新创建的项目,然后就加入当前的这个依赖

**Comment by devilsen** [comment]
> 好尴尬, 换成 0.4.4 编译是通过了,可是安装时候,一直卡在那里
> 
> <img alt="WX20190731-001629" width="1129" src="https://user-images.githubusercontent.com/10703130/62146705-856ba980-b328-11e9-8ee7-7d5f28663ce7.png">

你是在用虚拟机安装吗？现在lib不支持x86，是不能使用虚拟机的。如果还不行试试加上abiFilters。

**Comment by ipuppy2** [comment]
我是在真机安装的, 小米5s, android 8
abifilters 也添加了
安装报这个错:
2019-07-31 22:42:44.259 13537-13537/com.examp.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.examp.test, PID: 13537
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.examp.test/com.examp.test.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.examp.test.MainActivity" on path: DexPathList[[zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/lib/arm64, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2019-07-31 22:42:44.262 13537-13537/com.examp.test E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.examp.test.MainActivity" on path: DexPathList[[zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/lib/arm64, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2747)
            ... 9 more
        Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                ... 12 more
2019-07-31 22:42:44.266 13537-13537/com.examp.test E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/lib/arm64, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/base.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                ... 15 more
            Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
2019-07-31 22:42:44.270 13537-13537/com.examp.test E/AndroidRuntime:     at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5755)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
                    ... 6 more
            Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:681)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:714)
        at android.app.LoadedApk.getResources(LoadedApk.java:941)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2254)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5755)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1690)
                    ... 6 more
        [CIRCULAR REFERENCE:java.io.IOException: Failed to open dex files from /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk because: Failure to verify dex file '/data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_dependencies_apk.apk': Bad method handle type 7]
        [CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location /data/app/com.examp.test-Rc9oCmqyrt6LmrRvtwC-LQ==/split_lib_resources_apk.apk]

**Comment by ipuppy2** [comment]
build.gradle
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "cn.ipuppy.bb"
        minSdkVersion 26
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            // 设置支持的so库架构
            abiFilters "armeabi-v7a","arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'me.devilsen:CZXing:0.4.4'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

**Comment by ipuppy2** [comment]
build.gradle
`apply plugin: 'com.android.application'

android {
compileSdkVersion 28
defaultConfig {
applicationId "com.examp.test"
minSdkVersion 26
targetSdkVersion 28
versionCode 1
versionName "1.0"
testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
ndk {
// 设置支持的so库架构
abiFilters "armeabi-v7a","arm64-v8a"
}
}
buildTypes {
release {
minifyEnabled false
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
}
}
}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:design:28.0.0'
implementation 'com.android.support.constraint:constraint-layout:1.1.3'
testImplementation 'junit:junit:4.12'
implementation 'me.devilsen:CZXing:0.4.4'
androidTestImplementation 'com.android.support.test🏃1.0.2'
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
`

**Comment by ipuppy2** [comment]
没有加依赖,可以正常安装

**Comment by ipuppy2** [comment]
as版本: 3.4.2
![image](https://user-images.githubusercontent.com/10703130/62224939-0fc81200-b3ea-11e9-8e79-631cc90aaf1e.png)
![image](https://user-images.githubusercontent.com/10703130/62224963-1a82a700-b3ea-11e9-9701-37b43197971c.png)

**Comment by devilsen** [comment]
> as版本: 3.4.2
> ![image](https://user-images.githubusercontent.com/10703130/62224939-0fc81200-b3ea-11e9-8e79-631cc90aaf1e.png)
> ![image](https://user-images.githubusercontent.com/10703130/62224963-1a82a700-b3ea-11e9-9701-37b43197971c.png)

刚才模拟了你的问题，应该有两个解决方案，1.关闭Instant Run 2.把minSdkVersion设置为21。具体的原因还是要排查，你可以先用版本0.4.5试下。

**Comment by ipuppy2** [comment]
可以了,非常感谢
