### ISSUE TITLE
识别多次图片后,内存不足崩溃

### ISSUE THREAD

**Issue by xuhang1993** [devilsen/CZXing#120]
2020-08-24 13:45:10.047 30387-30418/com.hexfuture.hexcube E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: com.hexfuture.hexcube, PID: 30387
    java.lang.RuntimeException: OpenCV(4.0.1) /build/master_pack-android/opencv/modules/core/src/alloc.cpp:55: error: (-4:Insufficient memory) Failed to allocate 15411360 bytes in function 'OutOfMemoryError'
    
        at me.devilsen.czxing.code.NativeSdk.readBarcode(Native Method)
        at me.devilsen.czxing.code.BarcodeReader.read(BarcodeReader.java:62)
        at com.hexfuture.hexcube.scan.ui.HexCubeScanActivity.identifyCode(HexCubeScanActivity.kt:284)
        at com.hexfuture.hexcube.scan.ui.HexCubeScanActivity.access$identifyCode(HexCubeScanActivity.kt:61)
        at com.hexfuture.hexcube.scan.ui.HexCubeScanActivity$initScanListener$1.onPreview(HexCubeScanActivity.kt:216)
        at com.huagaoscan.sdk.impl.HGScanManagerImpl$1.run(HGScanManagerImpl.java:127)
        at java.lang.Thread.run(Thread.java:764)

**Comment by devilsen** [comment]
这是识别了多少次...

**Comment by xuhang1993** [comment]
200多次吧 业务要求识别每张图片二维码然后调用接口获取信息 
可以解决吗

**Comment by devilsen** [comment]
我看下，不过不太好复现。。不知道效果咋样

**Comment by xuhang1993** [comment]
要不我打包发给你二维码图片 你调试一下 怎么样

**Comment by xuhang1993** [comment]
你可以用多张二维码图片 重复识别 应该就会出现这种问题了

**Comment by devilsen** [comment]
嗯，也行，我看下

**Comment by xuhang1993** [comment]
我是识别200张双面的 应该是400多张图片

**Comment by xuhang1993** [comment]
感谢

**Comment by xuhang1993** [comment]
你好 这个问题解决了吗

**Comment by devilsen** [comment]
一直没找到问题，估计得先把 C++的知识补一补才行了。。。

**Comment by aohanhongzhi** [comment]
同样问题，小米11lite运行之后，大概扫了十几次就无法继续扫了。直接没有识别结果了。
![image](https://github.com/devilsen/CZXing/assets/37319319/4bc0acff-e6bd-4bc7-b7af-5535d72b12a1)

```java
2023-12-09 21:56:11.338 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4781(239KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 179us,40us total 45.188ms
2023-12-09 21:56:11.448 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:13.504 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:13.504 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4904(239KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 109us,77us total 44.644ms
2023-12-09 21:56:13.619 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:15.674 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:15.675 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4895(255KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 140us,106us total 54.180ms
2023-12-09 21:56:15.787 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:17.850 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:17.850 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4927(223KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 117us,87us total 51.186ms
2023-12-09 21:56:17.959 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:20.021 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:20.021 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4962(239KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 159us,84us total 50.473ms
2023-12-09 21:56:20.133 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:22.190 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:22.190 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4754(239KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 128us,78us total 49.848ms
2023-12-09 21:56:22.303 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)
2023-12-09 21:56:24.354 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  This is non sticky GC, maxfree is 8388608 minfree is 2097152
2023-12-09 21:56:24.354 22770-22793 devilsen.czxing         me.devilsen.czxing                   I  Explicit concurrent copying GC freed 4879(239KB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 204us,83us total 49.219ms
2023-12-09 21:56:24.467 22770-22793 LeakCanary              me.devilsen.czxing                   D  Rescheduling check for retained objects in 2000ms because found only 1 retained objects (< 5 while app visible)

```
