### ISSUE TITLE
打开扫描页面崩溃

### ISSUE THREAD

**Issue by Quyunshuo** [devilsen/CZXing#141]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuezhi.teachingassistant/me.devilsen.czxing.ScanActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class me.devilsen.czxing.view.ScanView`

**Comment by Quyunshuo** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yuezhi.teachingassistant/me.devilsen.czxing.ScanActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class me.devilsen.czxing.view.ScanView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3220)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3355)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2089)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:243)
        at android.app.ActivityThread.main(ActivityThread.java:7172)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class me.devilsen.czxing.view.ScanView
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class me.devilsen.czxing.view.ScanView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:908)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:467)
        at android.app.Activity.setContentView(Activity.java:2792)
        at me.devilsen.czxing.ScanActivity.onCreate(ScanActivity.java:56)
        at android.app.Activity.performCreate(Activity.java:7268)
        at android.app.Activity.performCreate(Activity.java:7259)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3200)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3355)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2089)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:243)
        at android.app.ActivityThread.main(ActivityThread.java:7172)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libiconv.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at me.devilsen.czxing.code.NativeSdk.<clinit>(NativeSdk.java:85)
        at me.devilsen.czxing.code.NativeSdk.getInstance(NativeSdk.java:17)
        at me.devilsen.czxing.code.BarcodeReader.<init>(BarcodeReader.java:30)
        at me.devilsen.czxing.code.BarcodeReader.getInstance(BarcodeReader.java:17)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:55)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:49)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:656) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:908) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:467) 
        at android.app.Activity.setContentView(Activity.java:2792) 
        at me.devilsen.czxing.ScanActivity.onCreate(ScanActivity.java:56) 
        at android.app.Activity.performCreate(Activity.java:7268) 
        at android.app.Activity.performCreate(Activity.java:7259) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3200) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3355) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2089) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:243) 
        at android.app.ActivityThread.main(ActivityThread.java:7172) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
```
