### ISSUE TITLE
 implementation project(':czxing') 缺少so文件

### ISSUE THREAD

**Issue by caobin821651400** [devilsen/CZXing#143]
将build改为下面这种，运行就会包缺少so文件 ，手机小米10 架构是arm64-v8a

   implementation project(':czxing')
//    implementation 'me.devilsen:czxing:1.0.17'

日志如下=====================
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libiconv.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
2021-01-05 09:51:16.373 13153-13153/? E/AndroidRuntime:     at me.devilsen.czxing.code.NativeSdk.<clinit>(NativeSdk.java:85)
        at me.devilsen.czxing.code.NativeSdk.getInstance(NativeSdk.java:17)
        at me.devilsen.czxing.code.BarcodeReader.<init>(BarcodeReader.java:30)
        at me.devilsen.czxing.code.BarcodeReader.getInstance(BarcodeReader.java:17)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:55)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:49)
        	... 28 more

**Comment by caobin821651400** [comment]
我去下载了1.0.0版本的没这个问题

**Comment by asdzheng** [comment]
缺少zbar了，新建个libs文件夹把zbar的库放到libs里吧，然后so库指向libs
