### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by caobin821651400** [devilsen/CZXing#19]
2019-08-06 09:23:09.664 4735-4735/me.devilsen.czxing E/CrashReport: stack frame :19, has cause false
2019-08-06 09:23:09.669 4735-4735/me.devilsen.czxing E/CrashReport: #++++++++++Record By Bugly++++++++++#
2019-08-06 09:23:09.669 4735-4735/me.devilsen.czxing E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
2019-08-06 09:23:09.669 4735-4735/me.devilsen.czxing E/CrashReport: # PKG NAME: me.devilsen.czxing
2019-08-06 09:23:09.669 4735-4735/me.devilsen.czxing E/CrashReport: # APP VER: 1.0
2019-08-06 09:23:09.670 4735-4735/me.devilsen.czxing E/CrashReport: # LAUNCH TIME: 2019-08-06 09:23:09
2019-08-06 09:23:09.670 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH TYPE: JAVA_CRASH
2019-08-06 09:23:09.670 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH TIME: 2019-08-06 09:23:09
2019-08-06 09:23:09.671 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH PROCESS: me.devilsen.czxing
2019-08-06 09:23:09.671 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH THREAD: main
2019-08-06 09:23:09.671 4735-4735/me.devilsen.czxing E/CrashReport: # REPORT ID: 606cdb5a-51ce-4cd5-811f-32da91dfa13c
2019-08-06 09:23:09.671 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH DEVICE: MI 6 UNROOT
2019-08-06 09:23:09.671 4735-4735/me.devilsen.czxing E/CrashReport: # RUNTIME AVAIL RAM:3064131584 ROM:34971996160 SD:34971996160
2019-08-06 09:23:09.672 4735-4735/me.devilsen.czxing E/CrashReport: # RUNTIME TOTAL RAM:6002479104 ROM:55291695104 SD:55291695104
2019-08-06 09:23:09.672 4735-4735/me.devilsen.czxing E/CrashReport: # CRASH STACK: 
2019-08-06 09:23:09.672 4735-4735/me.devilsen.czxing E/CrashReport: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.devilsen.czxing-K224nXmDTb203Ju-9y-_Tg==/base.apk"],nativeLibraryDirectories=[/data/app/me.devilsen.czxing-K224nXmDTb203Ju-9y-_Tg==/lib/arm, /data/app/me.devilsen.czxing-K224nXmDTb203Ju-9y-_Tg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libczxing.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at me.devilsen.czxing.BarcodeReader.<clinit>(BarcodeReader.java:131)
        at me.sam.czxing.MainActivity.onCreate(MainActivity.java:44)
        at android.app.Activity.performCreate(Activity.java:7232)
        at android.app.Activity.performCreate(Activity.java:7221)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6867)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
2019-08-06 09:23:09.672 4735-4735/me.devilsen.czxing E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by caobin821651400** [comment]
![image](https://user-images.githubusercontent.com/19204931/62504724-65f2e600-b82c-11e9-8c4d-0126a375e655.png)

**Comment by caobin821651400** [comment]
找到问题了，在sample.build里面加上arm64-v8a就可以了，应该是手机芯片不支持armeabi-v7a。

**Comment by devilsen** [comment]
芯片应该都是兼容的，只是NDK里面有好多坑😂
