### ISSUE TITLE
打开摄像头有时候会出现黑屏现象

### ISSUE THREAD

**Issue by cy757120553** [devilsen/CZXing#23]

**Comment by devilsen** [comment]
具体描述一下你的手机型号和版本，我找同类型手机测试下。

**Comment by cy757120553** [comment]
我这边是一个手持终端的设备，商米L2

**Comment by devilsen** [comment]
实在没有找到这样的设备，把日志贴出来我看下吧。

**Comment by woxingxiao** [comment]
@devilsen 识别速度很棒啊，多谢大佬。
我在测试过程中也发现了这个问题，反复启动扫描，基本有一半的几率出现黑屏。机型是魅族MX5和nubia Z7 mini，都是Android 5.1（ps：Android P的小米上完美运行），黑屏情况下的日志是：
```java
An error occurred while connecting to camera: 0
java.lang.RuntimeException: Fail to connect to camera service
    at android.hardware.Camera.<init>(Camera.java:525)
    at android.hardware.Camera.open(Camera.java:366)
    at me.devilsen.czxing.view.BarCoderView.startCameraById(BarCoderView.java:192)
    at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:160)
    at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
    at me.devilsen.czxing.view.BarCoderView.openCamera(BarCoderView.java:151)
    at me.devilsen.czxing.view.ScanView.openCamera(ScanView.java:23)
```
另外一个小建议，开启闪光灯的提示出现得有些频繁了，能否改进下真正光线不良时再提示开启。

**Comment by devilsen** [comment]
感谢反馈，我排查下。
