### ISSUE TITLE
sample直接依赖library出现闪退

### ISSUE THREAD

**Issue by ypkobe24** [devilsen/CZXing#27]
sample直接依赖library出现闪退。

2019-08-09 14:10:25.432 5994-5994/? E/CrashReport: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.devilsen.czxing-zyZLCGWUPDyoaZGyn9kHeg==/base.apk"],nativeLibraryDirectories=[/data/app/me.devilsen.czxing-zyZLCGWUPDyoaZGyn9kHeg==/lib/arm, /data/app/me.devilsen.czxing-zyZLCGWUPDyoaZGyn9kHeg==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libczxing.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at me.devilsen.czxing.BarcodeReader.<clinit>(BarcodeReader.java:131)
        at me.sam.czxing.MainActivity.onCreate(MainActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by ggggskd** [comment]
你没有编译c吧

**Comment by devilsen** [comment]
NDK环境是不是有问题？

**Comment by ypkobe24** [comment]
我以为只要依赖库就可以运行了，没有做过其他处理。除了添加依赖还需要哪些操作呢？------------------ 原始邮件 ------------------
发件人: "Codesam"<notifications@github.com>
发送时间: 2019年8月12日(星期一) 上午10:32
收件人: "devilsen/CZXing"<CZXing@noreply.github.com>;
抄送: "ypkobe24"<437206221@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [devilsen/CZXing] sample直接依赖library出现闪退 (#27)



NDK环境是不是有问题？
 
&mdash;
