### ISSUE TITLE
一运行就报错了

### ISSUE THREAD

**Issue by shangqianglong** [devilsen/CZXing#37]
2019-08-28 13:08:15.509 8309-8309/? E/CrashReport: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/base.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_dependencies_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_resources_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_0_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_1_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_2_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_3_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_4_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_5_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_6_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_7_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_8_apk.apk", zip file "/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/lib/arm, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/base.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/me.devilsen.czxing-wG-8YAo7sZpmYamqn-0pTg==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]] couldn't find "libczxing.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at me.devilsen.czxing.code.NativeSdk.<clinit>(NativeSdk.java:68)
        at me.devilsen.czxing.code.NativeSdk.getInstance(Unknown Source:0)
        at me.devilsen.czxing.code.BarcodeReader.<init>(BarcodeReader.java:17)
        at me.sam.czxing.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by devilsen** [comment]
是不是没有NDK环境？
