### ISSUE TITLE
打开扫码界面so错误

### ISSUE THREAD

**Issue by 1627762273** [devilsen/CZXing#5]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mochain.mvp-jzzmXeTq7BNAJ6B1p1gRkg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mochain.mvp-jzzmXeTq7BNAJ6B1p1gRkg==/lib/arm64, /data/app/com.mochain.mvp-jzzmXeTq7BNAJ6B1p1gRkg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libzxing-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at me.devilsen.czxing.BarcodeReader.<clinit>(BarcodeReader.java:134)
        at me.devilsen.czxing.processor.BarcodeProcessor.<init>(BarcodeProcessor.java:19)

**Comment by devilsen** [comment]
因为打包aar时只加入了armev7a，所以如果没有规定abiFilter会找不到v8下面的so，现在已经加入了v8版本，应该已经可以使用。
