### ISSUE TITLE
缩放Crash

### ISSUE THREAD

**Issue by JinruiWang** [devilsen/CZXing#51]
01-31 03:42:09.504 209-1242/? E/MtkCam/ParamsManager: [checkZoomValue] Invalid zoomValue(14), bigger than maxZoom(10) (checkZoomValue){#374:vendor/mediatek/proprietary/hardware/mtkcam/legacy/v1/common/paramsmgr/params/ParamsManager.check.cpp}
01-31 03:42:09.504 209-1242/? E/MtkCam/ParamsManager: [setParameters] checkParams() return -22 (setParameters){#325:vendor/mediatek/proprietary/hardware/mtkcam/legacy/v1/common/paramsmgr/params/ParamsManager.cpp}
01-31 03:42:09.508 1995-1995/cn.example E/MessageQueue-JNI: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2974)
        at me.devilsen.czxing.camera.CameraSurface.handleZoom(CameraSurface.java:251)
        at me.devilsen.czxing.camera.CameraSurface.doubleTap(CameraSurface.java:209)
        at me.devilsen.czxing.camera.CameraSurface.onTouchEvent(CameraSurface.java:122)

**Comment by devilsen** [comment]
放大的时候要判断一下MaxZoom的值，具体可以参看CameraSurface中的方法。
```java
Camera.Parameters params = mCamera.getParameters();
if (params.isZoomSupported()) {
    int zoom = params.getZoom();
    if (isZoomIn && zoom < params.getMaxZoom()) {
        zoom += scale;
    }
}
```

**Comment by devilsen** [comment]
已修复
