### ISSUE TITLE
9.10 报错

### ISSUE THREAD

**Issue by zhouhaoo** [devilsen/CZXing#82]
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:204)
        at android.content.res.Resources.getDrawable(Resources.java:899)
        at android.content.Context.getDrawable(Context.java:535)
        at me.devilsen.czxing.util.BitmapUtil.getBitmap(BitmapUtil.java:82)
        at me.devilsen.czxing.view.ScanBoxView.setFlashLightOnDrawable(ScanBoxView.java:506)
        at me.devilsen.czxing.ScanActivity.initData(ScanActivity.java:97)
        at me.devilsen.czxing.ScanActivity.onCreate(ScanActivity.java:78)
        at android.app.Activity.performCreate(Activity.java:6758)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)

**Comment by devilsen** [comment]
是不是少传资源文件了？
