### ISSUE TITLE
couldn't find "libczxing.so"

### ISSUE THREAD

**Issue by android140808** [devilsen/CZXing#95]
couldn't find "libczxing.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at me.devilsen.czxing.code.NativeSdk.<clinit>(NativeSdk.java:82)
        at me.devilsen.czxing.code.NativeSdk.getInstance(NativeSdk.java:17)
        at me.devilsen.czxing.code.BarcodeReader.<init>(BarcodeReader.java:32)
        at me.devilsen.czxing.code.BarcodeReader.getInstance(BarcodeReader.java:19)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:52)
        at me.devilsen.czxing.view.ScanView.<init>(ScanView.java:46)
        	... 28 more

**Comment by android140808** [comment]
what should I do ?

**Comment by lnkkk** [comment]
czing library去掉对"arm64-v8a"的ndk支持，可以解决，估计是在生成.so的时候 arm64-v8a里面的.so生成错误了吧

` externalNativeBuild {
            cmake {
//                cppFlags "-std=c++11 -frtti -fexceptions -pthread"
//                cppFlags "-std=c++11 -pthread"
                abiFilters "armeabi-v7a"
            }
        }`

**Comment by devilsen** [comment]
@android140808 是直接按照文档中的方式去引用的吗？

如果是引用代码的话需要NDK的环境，或者是生成so的配置、路径，这个问题要根据具体的gradle配置来解决。

**Comment by devilsen** [comment]
@android140808 刚才也遇到这个问题了，应该是AS的bug，clean一下重新引用就可以了。
